# Generated by Django 5.2.16 on 2026-08-13 09:21

import django.db.models.deletion
import utils.helpers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('azbankgateways', '0006_alter_bank_bank_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=utils.helpers.generate_unique_uuid, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('balance', models.PositiveBigIntegerField(default=0, verbose_name='موجودی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کیف پول',
                'verbose_name_plural': 'کیف پول ها',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=utils.helpers.generate_unique_uuid, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('tracking_code', models.CharField(max_length=255, verbose_name='کد پیگیری')),
                ('final_amount', models.PositiveBigIntegerField(verbose_name='مبلغ نهایی')),
                ('payment_method', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'پرداخت از کیف پول'), (2, 'پرداخت آنلاین')], default=2, verbose_name='روش پرداخت')),
                ('payment_for', models.PositiveSmallIntegerField(choices=[(1, 'شارژ کیف پول')], verbose_name='دلیل پرداخت')),
                ('object_id_for', models.PositiveBigIntegerField(blank=True, null=True)),
                ('result', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result', to='azbankgateways.bank', verbose_name='نتیجه درگاه پرداخت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر پرداخت کننده')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت ها',
                'indexes': [models.Index(fields=['user', 'created_at'], name='financial_p_user_id_0be427_idx'), models.Index(fields=['result', 'created_at'], name='financial_p_result__01fa0a_idx')],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=utils.helpers.generate_unique_uuid, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('tracking_code', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('is_processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tracking_code'], name='financial_w_trackin_0c40dd_idx'), models.Index(fields=['user', 'is_processed'], name='financial_w_user_id_1e4f16_idx')],
            },
        ),
    ]
