# Generated by Django 5.2.6 on 2025-09-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_alter_payment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='uuid',
            field=models.UUIDField(default='fcca030b-099b-4231-9d35-bbd53ea27964', editable=False, unique=True),
        ),
    ]
