# Generated by Django 5.2.16 on 2026-08-09 16:47

import apps.accounts.managers
import datetime
import django.db.models.deletion
import utils.helpers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=utils.helpers.generate_unique_uuid, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('request_id', models.UUIDField(db_index=True, default=utils.helpers.generate_unique_uuid, editable=False, unique=True)),
                ('channel', models.CharField(choices=[('p', 'Phone'), ('e', 'Email')], default='p', max_length=1, verbose_name='channel')),
                ('receiver', models.CharField(max_length=256)),
                ('password', models.CharField(blank=True, max_length=6, null=True)),
                ('expired_at', models.DateTimeField(db_index=True, default=datetime.datetime(2026, 8, 9, 16, 49, 54, 47271, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'verbose_name': 'درخواست رمز یکبار مصرف',
                'verbose_name_plural': 'درخواست رمز یکبار مصرف ها',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uuid', models.UUIDField(db_index=True, default=utils.helpers.generate_unique_uuid, editable=False, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='نام خانوادگی')),
                ('username', models.CharField(blank=True, editable=False, max_length=9, null=True, unique=True, verbose_name='نام کاربری')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='ایمیل')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='موبایل')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='رمز عبور')),
                ('is_staff', models.BooleanField(default=False, help_text='با این کزینه کاربر توانایی ورود به پنل مدیریت را دارا می باشد.', verbose_name='کاربر مدیر باشد؟')),
                ('is_active', models.BooleanField(default=False, help_text='Unselect this instead of deleting accounts.', verbose_name='فعال باشد؟')),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'کاربر معمولی')], default=1, verbose_name='نقش کاربر')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربر ها',
                'swappable': 'AUTH_USER_MODEL',
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=utils.helpers.generate_unique_uuid, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ آخرین لاگین')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip آخرین لاگین')),
                ('last_logout_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ آخرین خروج')),
                ('last_login_agent', models.TextField(blank=True, null=True, verbose_name='مرورگر آخرین ورود')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید ایمیل')),
                ('email_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تغییر ایمیل')),
                ('mobile_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تغییر موبایل')),
                ('mobile_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید موبایل')),
                ('username_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تغییر نام کاربری')),
                ('password_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تغییر رمز عبور')),
                ('is_banned', models.BooleanField(default=False, verbose_name='کاربر مسدود می باشد؟')),
                ('banned_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ مسدود شدن کاربر')),
                ('unbanned_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ رفع مسدودی ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=utils.helpers.generate_unique_uuid, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('avatar', models.ImageField(blank=True, default='images/default_man_avatar.jpg', null=True, upload_to='users/avatars/%Y/%m/%d/', verbose_name='تصویر پروفایل')),
                ('banner', models.ImageField(blank=True, default='images/default_banner.jpg', null=True, upload_to='users/banners/%Y/%m/%d/', verbose_name='بنر پروفایل')),
                ('gender', models.CharField(choices=[(None, 'نامشخص'), (1, 'آقا'), (2, 'خانم')], default='نامشخص', max_length=8, verbose_name='جنسیت')),
                ('bio', models.CharField(blank=True, max_length=255, null=True, verbose_name='بیوگرافی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل ها',
            },
        ),
    ]
