# Generated by Django 5.2.16 on 2026-08-23 08:32

import apps.accounts.managers
import datetime
import django.contrib.auth.models
import django.db.models.deletion
import utils.helpers
import utils.storage_paths
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanEditPost',
            fields=[
                ('permission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.permission')),
            ],
            bases=('auth.permission',),
            managers=[
                ('objects', django.contrib.auth.models.PermissionManager()),
            ],
        ),
        migrations.CreateModel(
            name='OtpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=utils.helpers.generate_unique_uuid, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('request_id', models.UUIDField(db_index=True, default=utils.helpers.generate_unique_uuid, editable=False, unique=True)),
                ('channel', models.CharField(choices=[('m', 'Mobile'), ('e', 'Email')], default='m', max_length=1, verbose_name='channel')),
                ('receiver', models.CharField(max_length=256)),
                ('password', models.CharField(blank=True, max_length=6, null=True)),
                ('expired_at', models.DateTimeField(db_index=True, default=datetime.datetime(2026, 8, 23, 8, 34, 52, 515413, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'verbose_name': 'درخواست رمز یکبار مصرف',
                'verbose_name_plural': 'درخواست رمز یکبار مصرف ها',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uuid', models.UUIDField(db_index=True, default=utils.helpers.generate_unique_uuid, editable=False, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='نام خانوادگی')),
                ('username', models.CharField(blank=True, editable=False, max_length=35, null=True, unique=True, verbose_name='نام کاربری')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='ایمیل')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='موبایل')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='رمز عبور')),
                ('is_staff', models.BooleanField(default=False, help_text='با این کزینه کاربر توانایی ورود به پنل مدیریت را دارا می باشد.', verbose_name='کاربر مدیر باشد؟')),
                ('is_active', models.BooleanField(default=False, help_text='با این گزینه کاربر فعال می باشد.', verbose_name='فعال باشد؟')),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'کاربر معمولی')], default=1, verbose_name='نقش کاربر')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربر ها',
                'swappable': 'AUTH_USER_MODEL',
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=utils.helpers.generate_unique_uuid, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('last_logout_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ آخرین خروج')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید ایمیل')),
                ('email_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تغییر ایمیل')),
                ('mobile_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تغییر موبایل')),
                ('mobile_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید موبایل')),
                ('is_banned', models.BooleanField(default=False, verbose_name='کاربر مسدود می باشد؟')),
                ('banned_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ مسدود شدن کاربر')),
                ('unbanned_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ رفع مسدودی ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=utils.helpers.generate_unique_uuid, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=utils.storage_paths.user_avatar_path, verbose_name='تصویر پروفایل')),
                ('banner', models.ImageField(blank=True, null=True, upload_to=utils.storage_paths.user_banner_path, verbose_name='بنر پروفایل')),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'نامشخص'), (2, 'آقا'), (3, 'خانم')], default=1, null=True, verbose_name='جنسیت')),
                ('short_bio', models.CharField(blank=True, max_length=100, null=True, verbose_name='تیتر شغلی یا تخصص')),
                ('bio', models.CharField(blank=True, max_length=255, null=True, verbose_name='بیوگرافی')),
                ('birthday_day', models.PositiveSmallIntegerField(blank=True, help_text='00', null=True, verbose_name='روز تولد')),
                ('birthday_month', models.PositiveSmallIntegerField(blank=True, help_text='00', null=True, verbose_name='ماه تولد')),
                ('birthday_year', models.PositiveSmallIntegerField(blank=True, help_text='0000', null=True, verbose_name='سال تولد')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل ها',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=utils.helpers.generate_unique_uuid, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('device', models.CharField(blank=True, max_length=20)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=50)),
                ('is_current', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ آخرین ورود')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_login_at'],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('follower', 'following')},
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=utils.helpers.generate_unique_uuid, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('provider', models.CharField(choices=[('github', 'Github'), ('gitlab', 'Gitlab'), ('bitbucket', 'Bitbucket'), ('google', 'Google')], verbose_name='provider')),
                ('provider_id', models.CharField(db_index=True, max_length=255)),
                ('provider_username', models.CharField(blank=True, max_length=255)),
                ('provider_email', models.EmailField(blank=True, max_length=254)),
                ('provider_avatar_url', models.URLField(blank=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('extra_data', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'حساب سوشیال',
                'verbose_name_plural': 'حسابهای سوشیال',
                'indexes': [models.Index(fields=['provider', 'provider_id'], name='accounts_so_provide_f59f70_idx'), models.Index(fields=['user', 'provider'], name='accounts_so_user_id_0a462a_idx')],
                'unique_together': {('user', 'provider')},
            },
        ),
    ]
