# Generated by Django 5.2.16 on 2026-08-30 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='expired_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 8, 30, 16, 56, 45, 787421, tzinfo=datetime.timezone.utc)),
        ),
    ]
