# Generated by Django 5.2.6 on 2025-09-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermeta',
            name='uuid',
            field=models.UUIDField(default='43a3a404-835c-44fb-aa08-221ade185034', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uuid',
            field=models.UUIDField(default='43a3a404-835c-44fb-aa08-221ade185034', editable=False, unique=True),
        ),
    ]
