# Generated by Django 5.2.16 on 2026-08-13 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='expired_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 8, 13, 13, 31, 59, 7390, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatars/%Y/%m/%d/', verbose_name='تصویر پروفایل'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='users/banners/%Y/%m/%d/', verbose_name='بنر پروفایل'),
        ),
    ]
