# Generated by Django 5.2.16 on 2026-08-31 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_otprequest_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='expired_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 8, 31, 17, 31, 4, 986279, tzinfo=datetime.timezone.utc)),
        ),
    ]
