# Generated by Django 5.2.6 on 2025-09-28 18:18

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usermeta_uuid_alter_userprofile_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default='e25c7ffd-a0f4-4815-8545-0c785d7561d7', editable=False, unique=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاریخ حذف')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('expired_at', models.DateTimeField(default=datetime.timedelta(seconds=180))),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('channel', models.CharField(choices=[('p', 'Phone'), ('e', 'Email')], default='p', max_length=20, verbose_name='channel')),
                ('receiver', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=4, null=True)),
                ('valid_until', models.DateTimeField(default=datetime.datetime(2025, 9, 28, 18, 20, 42, 464102, tzinfo=datetime.timezone.utc))),
                ('receipt_id', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Otp Request',
                'verbose_name_plural': 'Otp Requests',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربر ها'},
        ),
        migrations.AlterModelOptions(
            name='usermeta',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'پروفایل'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='uuid',
            field=models.UUIDField(default='e25c7ffd-a0f4-4815-8545-0c785d7561d7', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uuid',
            field=models.UUIDField(default='e25c7ffd-a0f4-4815-8545-0c785d7561d7', editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='AccountDeleteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default='e25c7ffd-a0f4-4815-8545-0c785d7561d7', editable=False, unique=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاریخ حذف')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('complete_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
