# Generated by Django 5.2.6 on 2025-09-28 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_activationcode_otprequest_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdeleterequest',
            name='uuid',
            field=models.UUIDField(default='9be97da4-584e-4473-a247-699c65f62287', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='activationcode',
            name='uuid',
            field=models.UUIDField(default='9be97da4-584e-4473-a247-699c65f62287', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='otprequest',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 28, 18, 21, 20, 652343, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='uuid',
            field=models.UUIDField(default='9be97da4-584e-4473-a247-699c65f62287', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uuid',
            field=models.UUIDField(default='9be97da4-584e-4473-a247-699c65f62287', editable=False, unique=True),
        ),
    ]
