# Generated by Django 5.2.6 on 2025-09-28 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_accountdeleterequest_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdeleterequest',
            name='uuid',
            field=models.UUIDField(default='fcca030b-099b-4231-9d35-bbd53ea27964', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='activationcode',
            name='uuid',
            field=models.UUIDField(default='fcca030b-099b-4231-9d35-bbd53ea27964', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='otprequest',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 28, 18, 23, 14, 504516, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='uuid',
            field=models.UUIDField(default='fcca030b-099b-4231-9d35-bbd53ea27964', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uuid',
            field=models.UUIDField(default='fcca030b-099b-4231-9d35-bbd53ea27964', editable=False, unique=True),
        ),
    ]
