# Generated by Django 5.2.16 on 2026-08-23 08:32

import django.db.models.deletion
import hitcount.models
import taggit_selectize.managers
import utils.helpers
import utils.storage_paths
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, help_text='به صورت خودکار ایجاد می شود!', max_length=255, unique=True, verbose_name='نامک')),
                ('description', models.TextField(blank=True, max_length=2048, null=True, verbose_name='توضیحات')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=utils.storage_paths.category_icon_path, verbose_name='آیکون')),
                ('is_active', models.BooleanField(default=True, verbose_name='دسته بندی فعال باشد?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='دسته بندی والد')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=utils.helpers.generate_unique_uuid, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='عنوان مقاله')),
                ('slug', models.SlugField(allow_unicode=True, default=None, unique=True, verbose_name='نامک')),
                ('short_description', models.TextField(max_length=255, verbose_name='توضیحات کوتاه')),
                ('body', models.TextField(verbose_name='متن مقاله')),
                ('thumbnail', models.ImageField(upload_to=utils.storage_paths.thumbnail_path, verbose_name='تصویر شاخص')),
                ('published_status', models.PositiveSmallIntegerField(choices=[(1, 'منتشر شده'), (2, 'پیش نویس')], default=2, verbose_name='وضعیت انتشار')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.category', verbose_name='دسته بندی')),
                ('tags', taggit_selectize.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='برچسب ها')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست ها',
                'indexes': [models.Index(fields=['title', 'body'], name='blog_post_title_aa1a72_idx')],
            },
            bases=(hitcount.models.HitCountMixin, models.Model),
        ),
    ]
