# Generated by Django 5.2.6 on 2025-09-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='uuid',
            field=models.UUIDField(default='9be97da4-584e-4473-a247-699c65f62287', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.UUIDField(default='9be97da4-584e-4473-a247-699c65f62287', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='uuid',
            field=models.UUIDField(default='9be97da4-584e-4473-a247-699c65f62287', editable=False, unique=True),
        ),
    ]
