# Generated by Django 5.2.6 on 2025-09-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comment_uuid_alter_post_uuid_alter_tag_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='uuid',
            field=models.UUIDField(default='fcca030b-099b-4231-9d35-bbd53ea27964', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.UUIDField(default='fcca030b-099b-4231-9d35-bbd53ea27964', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='uuid',
            field=models.UUIDField(default='fcca030b-099b-4231-9d35-bbd53ea27964', editable=False, unique=True),
        ),
    ]
